apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentapi
  namespace: ourpay
  labels:
    app: paymentapi
spec:
  replicas: 4  # 4 API instances for load balancing
  selector:
    matchLabels:
      app: paymentapi
  template:
    metadata:
      labels:
        app: paymentapi
    spec:
      containers:
      - name: paymentapi
        image: ourpay_v1-paymentapi:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ASPNETCORE_URLS
          value: "http://+:80"
        - name: ConnectionStrings__DefaultConnection
          value: "Host=postgres-service;Port=5432;Database=PaymentDb;Username=postgres;Password=postgres123"
        - name: RedisSettings__ConnectionString
          value: "redis-service:6379"
        - name: RabbitMQSettings__ConnectionString
          value: "amqp://guest:guest@rabbitmq-service:5672/"
        - name: JwtSettings__SecretKey
          value: "your-super-secret-jwt-key-that-is-at-least-256-bits-long-for-production-use"
        - name: JwtSettings__Issuer
          value: "PaymentAPI"
        - name: JwtSettings__Audience
          value: "PaymentAPI"
        - name: JwtSettings__ExpiryMinutes
          value: "15"
        - name: JwtSettings__RefreshTokenExpiryDays
          value: "7"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: paymentapi-service
  namespace: ourpay
spec:
  selector:
    app: paymentapi
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer  # This will distribute traffic across 4 API instances
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: paymentapi-ingress
  namespace: ourpay
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: paymentapi.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: paymentapi-service
            port:
              number: 80
